# -*- coding: utf-8 -*-
"""Quiz 1_Python_Data_Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bn-5baCoCurnyjdxBrg4d-1MmAMYd9q0
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import os
data =pd.read_csv('/content/drive/My Drive/Colab Notebooks/survey_results_public.csv')
data.head()

#სასურველი სვეტების გამოტანა ცხრილიდან
data = data[['Age', 'RemoteWork', 'YearsCode', 'Employment', 'DevType', 'Industry','ConvertedCompYearly', 'CodingActivities', 'Frequency_3', 'TimeSearching']]

#დაუნიშნეთ ინდექსირება ცხრილის კონკრეტული სვეტის მიმართ;
data.set_index('YearsCode')

#შექმნით 2 პარამეტრზე დამოკიდებულ ფილტრს. დაბეჭდეთ შესაბამისი ცხრილი.
filt = (data['Age'] == '18-24 years old') & (data['Employment'].str.startswith('Employed'))

data.loc[filt]

data.sort_values(by=['YearsCode', 'Industry'], ascending=[True, True], inplace=True)

data['ConvertedCompYearly'].std()
data['ConvertedCompYearly'].median()
data['ConvertedCompYearly'].min()
data['ConvertedCompYearly'].max()

import matplotlib.pyplot as plt
import numpy as np

frequency = data['Frequency_3'].value_counts()

plt.bar(frequency.index, frequency)
plt.xlabel('Frequency Type')
plt.ylabel('Count')
plt.title('different frequencys')

plt.show()

data
data['ConvertedCompYearly'] = data['ConvertedCompYearly'].apply(np.float64)
data['Age'] = data['Age'].apply(lambda x: 1 if not x.isdigit() else x)
plt.plot(data['ConvertedCompYearly'], data['Age'], marker='o', linestyle='-', color='blue')
plt.xlabel('Age')
plt.ylabel('Years of Coding Experience')
plt.title('Years of Coding Experience vs. Age')
plt.show()